@baseUrl = http://localhost:5268

GET {{baseUrl}}/weatherforecast/
Accept: application/json

###
GET {{baseUrl}}/hello
Accept: application/json

### todo all
GET {{baseUrl}}/api/todo
Accept: application/json

### Get specific todo
GET {{baseUrl}}/api/todo/1
Accept: application/json

### Create new todo
POST {{baseUrl}}/api/todo
Content-Type: application/json
{
  "title": "🦜",
  "isCompleted": true
}